<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13Rzx0f\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13Rzx0f/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container13Rzx0f.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container13Rzx0f\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container13Rzx0f\srcDevDebugProjectContainer(array(
    'container.build_hash' => '13Rzx0f',
    'container.build_id' => 'e98a6959',
    'container.build_time' => 1539165604,
), __DIR__.\DIRECTORY_SEPARATOR.'Container13Rzx0f');
